-------------------------------------------
--  DO NOT EDIT. This file is generated. --
-------------------------------------------

--  Copyright Fil Andrii root.fi36@gmail.com 2022-2025

--  Status generated by radio. 
pragma Ada_2022;


package Mavlink.V1.Ardupilotmega.Message.Radios is

   pragma Preelaborate;

   Radio_Id : constant Msg_Id := 166;

   Radio_Len : constant Interfaces.Unsigned_8 := 9;

   type Radio is record
      Rssi     : Interfaces.Unsigned_8;
      --  Local signal strength. 
      Remrssi  : Interfaces.Unsigned_8;
      --  Remote signal strength. 
      Txbuf    : Interfaces.Unsigned_8;
      --  Units: [%]
      --  How full the tx buffer is. 
      Noise    : Interfaces.Unsigned_8;
      --  Background noise level. 
      Remnoise : Interfaces.Unsigned_8;
      --  Remote background noise level. 
      Rxerrors : Interfaces.Unsigned_16;
      --  Receive errors. 
      Fixed    : Interfaces.Unsigned_16;
      --  Count of error corrected packets. 
   end record;

   for Radio use record
      Rxerrors at 0 range 0 .. 15;
      Fixed    at 2 range 0 .. 15;
      Rssi     at 4 range 0 .. 7;
      Remrssi  at 5 range 0 .. 7;
      Txbuf    at 6 range 0 .. 7;
      Noise    at 7 range 0 .. 7;
      Remnoise at 8 range 0 .. 7;
   end record;

   procedure Encode
     (Message : Radio;
      Connect : in out Mavlink.V1.Out_Connection;
      Buffer  : out Data_Buffer;
      Last    : out Positive);
   --  Put the message in the buffer ready for send

   procedure Encode
     (Message : Radio;
      Connect : in out Mavlink.V1.Connection;
      Buffer  : out Data_Buffer;
      Last    : out Positive);

   procedure Decode
     (Message   : out Radio;
      Connect   : in out Mavlink.V1.Connection;
      CRC_Valid : out Boolean);
   --  Get the message from the Connect and delete it
   --  from the Connect's buffer. CRC_Valid is set to
   --  True if x25crc is valid for the message.

   procedure Decode
     (Message : out Radio;
      Connect : in out Mavlink.V1.Connection);
   --  Same as Above but does not check CRC

   function Check_CRC
     (Connect : in out Mavlink.V1.Connection)
      return Boolean;
   --  Returns True if CRC is valid

end Mavlink.V1.Ardupilotmega.Message.Radios;
