-------------------------------------------
--  DO NOT EDIT. This file is generated. --
-------------------------------------------

--  Copyright Fil Andrii root.fi36@gmail.com 2022-2025

--  Status generated by radio.

pragma Ada_2022;

package MAVLink.V1.Ardupilotmega.Radios is

   pragma Pure;

   Radio_Len : constant Interfaces.Unsigned_8 := 9;

   type Radio is record
      Rssi     : Interfaces.Unsigned_8;
      --  Local signal strength.
      Remrssi  : Interfaces.Unsigned_8;
      --  Remote signal strength.
      Txbuf    : Interfaces.Unsigned_8;
      --  Units: [%]
      --  How full the tx buffer is.
      Noise    : Interfaces.Unsigned_8;
      --  Background noise level.
      Remnoise : Interfaces.Unsigned_8;
      --  Remote background noise level.
      Rxerrors : Interfaces.Unsigned_16;
      --  Receive errors.
      Fixed    : Interfaces.Unsigned_16;
      --  Count of error corrected packets.
   end record;

   for Radio use record
      Rxerrors at 0 range 0 .. 15;
      Fixed    at 2 range 0 .. 15;
      Rssi     at 4 range 0 .. 7;
      Remrssi  at 5 range 0 .. 7;
      Txbuf    at 6 range 0 .. 7;
      Noise    at 7 range 0 .. 7;
      Remnoise at 8 range 0 .. 7;
   end record;

   procedure Encode
     (Message : Radio;
      Connect : in out MAVLink.V1.Out_Connection;
      Buffer  : out Data_Buffer;
      Last    : out Positive);
   --  Put the message in the buffer ready for send

   procedure Encode
     (Message : Radio;
      Connect : in out MAVLink.V1.Connection;
      Buffer  : out Data_Buffer;
      Last    : out Positive);

   procedure Decode
     (Message   : out Radio;
      Connect   : in out MAVLink.V1.Connection;
      CRC_Valid : out Boolean);
   --  Get the message from the Connect and delete it
   --  from the Connect's buffer. CRC_Valid is set to
   --  True if x25crc is valid for the message.

   procedure Decode
     (Message : out Radio;
      Connect : MAVLink.V1.Connection);
   --  Same as Above but does not check CRC

   procedure Decode
     (Message   : out Radio;
      Connect   : in out MAVLink.V1.In_Connection;
      CRC_Valid : out Boolean);
   --  Get the message from the Connect and delete it
   --  from the Connect's buffer. CRC_Valid is set to
   --  True if x25crc is valid for the message.

   procedure Decode
     (Message : out Radio;
      Connect : MAVLink.V1.In_Connection);
   --  Same as Above but does not check CRC

   function Check_CRC
     (Connect : in out MAVLink.V1.Connection)
      return Boolean with Inline;
   --  Returns True if CRC is valid

   function Check_CRC
     (Connect : in out MAVLink.V1.In_Connection)
      return Boolean with Inline;
   --  Returns True if CRC is valid

end MAVLink.V1.Ardupilotmega.Radios;
