-------------------------------------------
--  DO NOT EDIT. This file is generated. --
-------------------------------------------

--  Status generated by radio and injected into MAVLink stream.

pragma Ada_2022;

with MAVLink.V2.Common.Radio_Statuses;

package MAVLink.V2.Cubepilot.Radio_Statuses
renames MAVLink.V2.Common.Radio_Statuses;
